package com.google.errorprone.bugpatterns;

import com.google.errorprone.CompilationTestHelper;

import org.junit.Before;
import org.junit.Test;

import java.io.File;

/**
 * TODO: Insert description here. (generated by sgoldfeder)
 */
public class GuiceMoreThanOneInjectableConstructorTest {

  private CompilationTestHelper compilationHelper;

  @Before
  public void setUp() {
    compilationHelper = new CompilationTestHelper(new GuiceMoreThanOneInjectableConstructor.Scanner());
  }

  @Test
  public void testPositiveCase() throws Exception {
    compilationHelper.assertCompileFailsWithMessages(
        new File(this.getClass().getResource("GuiceMoreThanOneInjectableConstructorPositiveCases.java")
            .toURI()));
  }

  @Test
  public void testNegativeCase() throws Exception {
    compilationHelper.assertCompileSucceeds(
        new File(this.getClass().getResource("GuiceMoreThanOneInjectableConstructorNegativeCases.java")
            .toURI()));
  }
}